<?php

namespace AppBundle\Repository;

/**
 * EpowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpowerRepository extends \Doctrine\ORM\EntityRepository
{
}
