<?php

namespace AppBundle\Repository;

/**
 * GasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GasRepository extends \Doctrine\ORM\EntityRepository
{
}
