<?php

namespace AppBundle\Repository;

/**
 * WaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaterRepository extends \Doctrine\ORM\EntityRepository
{
}
